Version adapter and test fixes
randovania/mercury-engine-data-structures pull request #186
Opened 2024-07-20 17:58 UTC by steven11sjf

Fixes #30 #184 

Added an adapter that converts a standard version field (Int16ul major, Int8 minor, Int8 patch) to a tuple or string "M.m.p" and optionally validates it against an expected version. This is applied to all places where a version field exists. 

Fixed a bug where standard_format.game_model ignores the provided name and version field passed to it. Additionally, standard_format.create uses the new VersionAdapter. 

Added  parse/build for Dread .BMDEFS using a standard_format

Added a function to dread_data and samus_returns_data to return all files with a specified file extension. Replaces a large amount of code in test parametrization

Fixed some tests that were only testing on a subset of files (Bmssd, Bmbls, Bctex)

Fixed BCTEX skipping textures in packages

Removed test_lib functions that operate only on romfs files, since using the FileTreeEditor will cover these files and any in the packages

Added/simplified some checks to skip missing files

2024-07-20 18:16 UTC, henriquegemignani requested changes

2024-07-20 18:16 UTC, henriquegemignani commented on tests/formats/test_bmsld.py
> +@pytest.mark.parametrize("bmsld_path", samus_returns_data.all_files_ending_with(".bmsld"))
Delete all_bmsld then

2024-07-20 18:16 UTC, henriquegemignani commented on tests/formats/test_pkg.py
> +    parse_build_compare_editor(Pkg, dread_file_tree, pkg_path)
I'd rather the Pkg tests not use the FileTreeEditor, because that one uses Pkg a lot internally

2024-07-20 18:18 UTC, henriquegemignani reviewed
There's a lot more of tests that automatically skip for missing files. Is there a way to know which of the file names we expect to be missing from the romfs? Because I'd prefer to fail a test if the file happens to be missing.

2024-07-20 18:23 UTC, steven11sjf commented
I can add lists of missing files to check against, will take a minute though

2024-07-21 23:12 UTC, henriquegemignani requested changes

2024-07-21 23:12 UTC, henriquegemignani commented on tests/formats/test_bmssd.py
> +    if bmssd_path in sr_missing:
Can you exclude the path from the parametrize, instead of skipping the test? Should make it cleaner overall with less skipped tests, plus be faster.

2024-07-22 07:29 UTC, henriquegemignani approved these changes

2024-07-22 07:31 UTC, merged