Add BMSEV
randovania/mercury-engine-data-structures pull request #205
Opened 2024-08-03 08:29 UTC by ThanatosGit

Simple format but no idea what this is for or what is the meaning of all the floats.
Don't know if it makes sense to merge it like that but I leave it here for now.

Fixes #166 

Example:
```
Container: 
    magic = b'MSEV' (total 4)
    version = u'1.9.0' (total 5)
    elements = ListContainer: 
        Container: 
            name = u'exterior' (total 8)
            unknown_floats = ListContainer: 
                1.0
                0.5932559967041016
                0.6855469942092896
                0.16550900042057037
                1.0
                1.0
                3.5
                0.0
                2.0
                0.12156900018453598
                0.1210940033197403
                0.12156900018453598
                1.0
                0.0
                2.0
                0.5529410243034363
                0.5333330035209656
                0.5529410243034363
                -100.0
                0.0
                2.0
                0.0
                0.0
                0.0
                1.0
                0.0
                0.0
                0.0
                0.0
                0.0
                0.0
                0.0
                1.0
                0.0
                0.0
                0.0
                1.0
                0.0
                0.0
                0.0
                1.0
                0.0
                0.0
                0.0
                0.0
                1.0
                0.32548999786376953
                0.37254899740219116
                0.21960799396038055
                1.0
                0.19607800245285034
                0.137254998087883
                0.10196100175380707
                0.0
                0.0
                0.09411799907684326
                0.09411799907684326
                0.09411799907684326
                0.0
        Container: 
            name = u'cueva01' (total 7)
            unknown_floats = ListContainer: 
                2.0
                0.4156860113143921
                0.5098040103912354
                0.21568599343299866
                1.0
                2.0
                2.5625
                0.0
                2.0
                0.17647099494934082
                0.17647099494934082
                0.20000000298023224
                1.0
                0.0
                2.0
                0.47843098640441895
                0.37254899740219116
                0.2901960015296936
                -100.0
                0.0
                2.0
                0.0
                0.0
                0.0
                1.0
                0.0
                0.0
                0.0
                0.0
                0.0
                0.0
                0.0
                1.0
                0.0
                0.0
                0.0
                1.0
                0.0
                0.0
                0.0
                1.0
                0.0
                0.0
                0.0
                0.0
                1.0
                0.18431399762630463
                0.20784300565719604
                0.1254899948835373
                1.0
                0.10980399698019028
                0.09411799907684326
                0.08627499639987946
                0.0
                0.0
                0.11999999731779099
                0.11999999731779099
                0.11999999731779099
                0.0
        Container: 
            name = u'default' (total 7)
            unknown_floats = ListContainer: 
                2.0
                0.3803919851779938
                0.4666669964790344
                0.19215700030326843
                1.0
                2.0
                1.7999999523162842
                0.0
                2.0
                0.20000000298023224
                0.20000000298023224
                0.20000000298023224
                1.0
                0.0
                0.0
                0.23137299716472626
                0.21960799396038055
                0.18431399762630463
                -100.0
                0.0
                2.0
                0.0
                0.0
                0.0
                1.0
                0.0
                0.0
                0.0
                0.0
                0.0
                0.0
                0.0
                1.0
                0.0
                0.0
                0.0
                1.0
                0.0
                0.0
                0.0
                1.0
                0.0
                0.0
                0.0
                0.0
                1.0
                0.20000000298023224
                0.34902000427246094
                0.17647099494934082
                1.0
                0.22352899610996246
                0.1529410034418106
                0.058823999017477036
                0.0
                0.0
                0.11999999731779099
                0.11999999731779099
                0.11999999731779099
                0.0
        Container: 
            name = u'chozoroom01' (total 11)
            unknown_floats = ListContainer: 
                1.0
                0.4666669964790344
                0.6313729882240295
                0.11372499912977219
                1.0
                1.0
                2.625
                0.0
                1.0
                0.20000000298023224
                0.20000000298023224
                0.20000000298023224
                1.0
                0.0
                1.0
                0.38431400060653687
                0.35686299204826355
                0.3294120132923126
                -120.0
                0.0
                1.0
                0.0
                0.0
                0.0
                1.0
                1.0
                0.0
                0.0
                1.0
                0.0
                0.0
                0.0
                1.0
                0.0
                0.0
                0.0
                1.0
                0.0
                0.0
                0.0
                1.0
                1.0
                0.0
                0.0
                0.0
                1.0
                0.07058800011873245
                0.07843100279569626
                0.031373001635074615
                1.0
                0.1568630039691925
                0.08235300332307816
                0.08235300332307816
                0.0
                1.0
                0.11999999731779099
                0.11999999731779099
                0.11999999731779099
                0.0
        Container: 
            name = u'hazarousExt' (total 11)
            unknown_floats = ListContainer: 
                1.0
                0.2980389893054962
                0.11372499912977219
                0.47843098640441895
                1.0
                1.0
                0.9375
                0.0
                2.0
                0.10196100175380707
                0.10196100175380707
                0.10196100175380707
                1.0
                0.0
                1.0
                0.34902000427246094
                0.3098039925098419
                0.4588240087032318
                -101.0
                0.0
                1.0
                0.0
                0.0
                0.0
                1.0
                1.0
                0.0
                0.0
                0.0
                0.0
                0.0
                0.0
                1.0
                0.0
                0.0
                0.0
                1.0
                0.0
                0.0
                0.0
                1.0
                0.0
                0.0
                0.0
                0.0
                1.0
                0.24706999957561493
                0.20000000298023224
                0.32548999786376953
                1.0
                0.08627499639987946
                0.0
                0.2941179871 [...]

2024-08-03 15:51 UTC, duncathan requested changes
is it even known what this file is for? lol

2024-08-03 15:51 UTC, duncathan commented on src/mercury_engine_data_structures/formats/bmsev.py
> +    "elements" / make_vector(Struct(
this can probably use `make_dict()` instead

2024-08-03 17:01 UTC, steven11sjf commented
Compare it with dread's BREV, I assume its the same thing but not using reflection system. 

https://github.com/randovania/mercury-engine-data-structures/blob/bbce1777b4b3a4b77499dd91fcca41249f5dc075/src/mercury_engine_data_structures/dread_types.json#L12968

I'd need to count fields to figure it out for sure but it looks like floats[1:4] may be the fog color. and probably a couple other colors in there as well.

2025-02-27 23:25 UTC, ThanatosGit commented
> Would be preferable to clean up and name all of these values.

That's fair.
But tbh: A format I don't care about and don't need will never ever be high enough on my priority list to further work on it. Then I just stop it here and whenever anyone wants to work on it, it's here in the history.

2025-02-27 23:25 UTC, closed without merging